pipelines = {
    'bead': [
        'bead_stack_nr',
        'bead_stack_1',
        'bead_stack_2',
        'bead_stack_3',
        'bead_stack_4',
        'bead_stack',
    ],
    'shelf': [
        'shelf_nr',
        'shelf_55',
        # 'shelf_75',
        'shelf_95',
        # 'shelf_115',
        # 'shelf_135',
        'shelf_155',
        'shelf_200',
        'shelf_250',
        'shelf_300',
        'shelf',
    ],
    'wall': [
        'reach_no_wall',
        'row_7',
        'row_13',
        'row_19',
        'row_25',
        'row_31',
        'row_37',
        'row_43',
        'row_49',
        'row_55',
        'row_61',
        'row_67',
        'reach_over_wall_static',
    ],
    'rack': [
        'dish_rack_nr',
        'dish_rack_pr_14',
        'dish_rack_pr_16',
        'dish_rack_pr_18',
        'dish_rack_pr_20',
        'dish_rack_pr_22',
        'dish_rack',
    ],
}
